server {
    listen 80;

    client_max_body_size 50M;

    # Endpoint para Crear Denuncias (Va al Command Service)
    # POST /api/complaints -> http://command-service:3001/complaints
    location /api/complaints {
        proxy_pass http://command-service:3001/complaints;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Solo permitimos POST aquí (CQRS estricto)
        limit_except POST {
            deny all;
        }
    }

    # Endpoint para Leer Denuncias (Va al Query Service)
    # GET /api/query/complaints -> http://query-service:3002/complaints
    location /api/query/ {
        # Reescribimos la URL para quitar el prefijo /api/query
        rewrite ^/api/query/(.*) /$1 break;
        proxy_pass http://query-service:3002;
        proxy_set_header Host $host;
    }
}