server {
    listen 80;

    client_max_body_size 50M;

    # --- 1. Endpoint para Crear Denuncias (Command Service) ---
    # POST /api/complaints -> http://127.0.0.1:3001/complaints
    location /api/complaints {
        proxy_pass http://127.0.0.1:3001/complaints;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Solo permitimos POST (CQRS)
        limit_except POST {
            deny all;
        }
    }

    # --- 2. Endpoint para Crear Usuarios (NUEVO) ---
    # POST /api/users -> http://127.0.0.1:3001/users
    location /api/users {
        proxy_pass http://127.0.0.1:3001/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Solo permitimos POST (Para registrar usuarios)
        limit_except POST {
            deny all;
        }
    }

    # --- 3. Endpoint para Leer Datos (Query Service) ---
    # GET /api/query/... -> http://127.0.0.1:3002/...
    location /api/query/ {
        # Reescribimos la URL para quitar el prefijo /api/query
        rewrite ^/api/query/(.*) /$1 break;
        proxy_pass http://127.0.0.1:3002;
        proxy_set_header Host $host;
    }
}